{
  inputs,
  pkgs,
  lib,
  config,
  modulesPath,
  ...
}: {
  ##############################################################################
  # IMPORTS
  ##############################################################################

  imports = [
    inputs.nixos-hardware.nixosModules.asus-zephyrus-gu603h
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  ##############################################################################
  # BOOT & FILESYSTEMS
  ##############################################################################

  # boot.binfmt.emulatedSystems = ["aarch64-linux"]; # Cross compile for arm
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev";
    configurationLimit = 10;
    timeoutStyle = "hidden"; # hold shift to show nixos generations
    splashImage = null;
  };
  # boot.initrd.verbose = false;
  # boot.plymouth.enable = true;
  # boot.consoleLogLevel = 0;
  # boot.kernelParams = ["quiet" "udev.log_level=0"];

  # Auto-generated by nixos-generate-config
  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1dd7da41-6611-4227-be23-5f63d396e921";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8F98-0342";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/d33cb675-34b1-4054-a9a0-4cd9e50833b5";}
  ];

  ##############################################################################
  # HARDWARE
  ##############################################################################

  # Disable nvidia (commented out)
  # boot.blacklistedKernelModules = [
  #   "nvidia"
  #   "nvidiafb"
  #   "nvidia-drm"
  #   "nvidia-uvm"
  #   "nvidia-modeset"
  # ];
  # services.xserver.videoDrivers = [];

  # Nvidia
  # Very experimental
  # hardware.nvidia.powerManagement.enable = true;
  # hardware.nvidia.powerManagement.finegrained = true;
  hardware.nvidia.open = false;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;
  # hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.latest;

  # Graphics
  hardware.graphics.enable32Bit = true;

  # CPU
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Bluetooth
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;

  ##############################################################################
  # POWER MANAGEMENT
  ##############################################################################

  services.power-profiles-daemon.enable = false;
  services.auto-cpufreq.enable = false;
  services.tlp.enable = true;
  services.tlp.settings = {
    # Aggressive power saving settings
    CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
    CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
    SCHED_POWERSAVE_ON_BAT = 1;
    WIFI_PWR_ON_BAT = "on";
    PCIE_ASPM_ON_BAT = "powersupersave";
    RUNTIME_PM_ON_BAT = "auto";
    SOUND_POWER_SAVE_ON_BAT = 1;
    SOUND_POWER_SAVE_CONTROLLER = "Y";
  };

  ##############################################################################
  # NETWORKING
  ##############################################################################

  networking.networkmanager.enable = true;
  networking.networkmanager.plugins = [pkgs.networkmanager-openvpn];
  networking.hostName = "frostmourne";
  networking.firewall.enable = false;
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  networking.interfaces."lo".ipv4.addresses = [
    {
      address = "127.0.0.2";
      prefixLength = 32;
    }
  ];

  networking.stevenblack = {
    enable = false;
    block = ["fakenews" "gambling" "porn" "social"];
  };

  # Nginx reverse proxy
  services.nginx = {
    enable = true;
    virtualHosts."localhost" = {
      forceSSL = false;
      listen = [
        {
          addr = "0.0.0.0";
          port = 80;
        }
      ];
      locations."/".proxyPass = "http://127.0.0.1:8001";
      locations."/mirror/core".proxyPass = "http://127.0.0.1:8002";
      locations."/mirror/report".proxyPass = "http://127.0.0.1:8003";
      locations."/mirror/ai".proxyPass = "http://127.0.0.1:8004";
      # locations."/mirror/payment".proxyPass = "http://127.0.0.1:8005";
      locations."/mirror/payment/" = {
        proxyPass = "http://127.0.0.1:8005/";
        extraConfig = ''
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Prefix /mirror/payment;
          proxy_set_header X-Forwarded-Proto $scheme;
        '';
      };
      locations."/mirror/calendar".proxyPass = "http://127.0.0.1:8006";
    };
    # virtualHosts."frostmourne.local" = {
    #   enableACME = true;
    #   forceSSL = true;
    #   root = "/var/www/dashboard";
    # };
  };
  security.acme = {
    acceptTerms = true;
    defaults.email = "saegl@protonmail.com";
  };

  # Avahi (mDNS / zeroconf)
  # Interesting, but unstable
  services.avahi = {
    # enable = true;
    nssmdns4 = true;
    openFirewall = true;
    publish = {
      enable = true;
      addresses = true;
      domain = true;
      hinfo = true;
      userServices = true;
      workstation = true;
    };
  };

  # SSH
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.KbdInteractiveAuthentication = false;
    settings.AllowUsers = ["*@192.168.*.*"];
  };

  ##############################################################################
  # LOCALE & TIME
  ##############################################################################

  time.timeZone = "Asia/Ashgabat"; # Return to "Asia/Almaty" when updated from +6 to +5
  i18n.defaultLocale = "en_US.UTF-8";

  ##############################################################################
  # USERS
  ##############################################################################

  users.users.saegl = {
    isNormalUser = true;
    shell = pkgs.fish;
    extraGroups = [
      "wheel"
      "video"
      "audio"
      "input"
      "docker"
    ];
    createHome = true;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEOd0Z22qitTvXUwAVMAi5EyqV6b69flhLL28Cde2VpV nix-on-droid"
    ];
  };

  ##############################################################################
  # PROGRAMS
  ##############################################################################

  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
  };

  programs.git = {
    enable = true;
    lfs.enable = true;
  };

  programs.fish = {
    enable = true;
    generateCompletions = true;
    vendor = {
      config.enable = true;
      functions.enable = true;
      completions.enable = true;
    };
  };

  programs.zoxide.enable = true; # Fuzzy finder between dirs with "z"
  programs.yazi.enable = true; # file manager

  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  # programs.adb.enable = true; # Migrate to `pkgs.android-tools`
  programs.java.enable = true;

  # programs.ghidra = {
  #   enable = true;
  #   gdb = true;
  #   package = pkgs.ghidra.withExtensions (exts:
  #     with exts; [
  #       gnudisassembler
  #     ]);
  # };

  programs.niri.enable = true;
  # programs.river.enable = false;
  # programs.river.extraPackages = [];

  programs.nh = {
    enable = true;
    flake = "/home/saegl/projects/nix/nixos";
  };

  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    alsa-lib
    at-spi2-atk
    at-spi2-core
    atk
    cairo
    cups
    curl
    expat
    fontconfig
    freetype
    fuse3
    gdk-pixbuf
    glib
    gtk3
    icu
    libGL
    libappindicator-gtk3
    libdrm
    libglvnd
    libnotify
    libpulseaudio
    libunwind
    libusb1
    libuuid
    libxkbcommon
    libxml2
    libdbusmenu
    dbus
    krb5
    mesa
    nspr
    nss
    openssl
    pango
    pipewire
    stdenv.cc.cc
    systemd
    vulkan-loader
    libx11
    libxscrnsaver
    libxcomposite
    libxcursor
    libxdamage
    libxext
    libxfixes
    libxi
    libxrandr
    libxrender
    libxtst
    libxcb
    libxkbfile
    libxshmfence
    libxinerama
    qt6.qtbase
    qt6.qtwayland
    libxcb
    zlib
  ];

  # Gaming
  programs.gamemode.enable = true;
  programs.gamemode.enableRenice = true;
  programs.gamescope.enable = true;
  programs.gamescope.capSysNice = true;
  programs.gamescope.args = [
    "--rt" # Real time priority
    # "--prefer-vk-device 10de:25a0" # Use the NVIDIA GeForce RTX 3050 Ti Mobile
    "-W"
    "2560"
    "-H"
    "1600"
    "-r"
    "165"
  ];
  # programs.gamescope.env = {
  #   __NV_PRIME_RENDER_OFFLOAD = "1";
  #   __NV_PRIME_RENDER_OFFLOAD_PROVIDER = "NVIDIA-G0";
  #   __GLX_VENDOR_LIBRARY_NAME = "nvidia";
  #   __VK_LAYER_NV_optimus = "NVIDIA_only";
  # };
  programs.steam.enable = true;
  programs.steam.gamescopeSession.enable = true;
  programs.steam.remotePlay.openFirewall = true;
  programs.steam.dedicatedServer.openFirewall = true;
  programs.steam.extraPackages = with pkgs; [
    libxcursor
    libxi
    libxinerama
    libxscrnsaver
    libpng
    libpulseaudio
    libvorbis
    stdenv.cc.cc.lib
    libkrb5
    keyutils
  ];

  programs.virt-manager.enable = false;

  ##############################################################################
  # SERVICES
  ##############################################################################

  services.devmon.enable = true; # automount usb to /run/media/saegl/<name>/
  services.asusd.enable = true;
  services.logind.settings.Login.HandleLidSwitch = "ignore";
  services.libinput.enable = true;
  services.libinput.touchpad.naturalScrolling = true;

  # Sound
  services.pulseaudio.enable = false;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Bluetooth
  services.blueman.enable = true;

  # Database services
  services.postgresql.package = pkgs.postgresql_14;
  services.pgadmin.enable = true;
  services.pgadmin.initialEmail = "zhubanysh.alisher@gmail.com";
  services.pgadmin.initialPasswordFile = "/home/saegl/projects/ff/dash/psqlpass.txt";

  # services.mongodb = {
  #   enable = true;
  #   replSetName = "rs0";
  #   bind_ip = "127.0.0.1";
  # };

  # services.ollama.enable = true;

  # Glance dashboard
  # services.glance.enable = true;
  # systemd.services.glance = {
  #   serviceConfig = {
  #     ExecStart = "${pkgs.glance}/bin/glance --config /home/saegl/.config/glance/glance.yml";
  #   };
  # };

  # Desktop services
  services.gnome.gnome-keyring.enable = true; # Maybe does something for mongodb-compass
  services.dbus.enable = true;

  # X11 (disabled, using wayland)
  services.xserver.enable = false;
  services.xserver.xkb.layout = "us,ru";
  services.xserver.xkb.options = "grp:alt_shift_toggle";

  ##############################################################################
  # VIRTUALISATION
  ##############################################################################

  virtualisation.docker.enable = true;
  virtualisation.libvirtd.enable = false;

  ##############################################################################
  # SECURITY
  ##############################################################################

  security.rtkit.enable = true;
  security.pam.services.swaylock = {};

  ##############################################################################
  # XDG PORTAL
  ##############################################################################

  xdg.portal = {
    enable = true;
    config = {
      common = {
        default = ["gnome" "gtk"];
      };
      niri = {
        default = ["gnome" "gtk"];
        "org.freedesktop.impl.portal.ScreenCast" = ["gnome"];
        "org.freedesktop.impl.portal.Screenshot" = ["gnome"];
        "org.freedesktop.impl.portal.FileChooser" = ["gtk"];
      };
    };
    extraPortals = [
      pkgs.xdg-desktop-portal-gnome
      pkgs.xdg-desktop-portal-gtk
    ];
  };

  # Fix niri portals autostart order
  # See https://github.com/sodiboo/niri-flake/issues/509
  systemd.user.services.xdg-desktop-portal = {
    after = ["xdg-desktop-autostart.target"];
  };
  systemd.user.services.xdg-desktop-portal-gtk = {
    after = ["xdg-desktop-autostart.target"];
  };
  systemd.user.services.xdg-desktop-portal-gnome = {
    after = ["xdg-desktop-autostart.target"];
  };
  systemd.user.services.niri-flake-polkit = {
    after = ["xdg-desktop-autostart.target"];
  };

  ##############################################################################
  # XDG MIME
  ##############################################################################

  # xdg.enable = true;
  xdg.mime.enable = true;
  xdg.mime.defaultApplications = {
    "image/svg+xml" = "org.gnome.Loupe.desktop";
    "image/png" = "org.gnome.Loupe.desktop";
    "image/jpeg" = "org.gnome.Loupe.desktop";
    "image/jpg" = "org.gnome.Loupe.desktop"; # Optional: 'jpg' is technically just a common extension for 'jpeg'
    "application/pdf" = "org.pwmt.zathura.desktop";
    "application/postscript" = "org.pwmt.zathura.desktop";
    "application/vnd.comicbook+zip" = "org.pwmt.zathura.desktop";
    "application/vnd.comicbook-rar" = "org.pwmt.zathura.desktop";
    "application/vnd.ms-xpsdocument" = "org.pwmt.zathura.desktop";
    "application/x-bzpdf" = "org.pwmt.zathura.desktop";
    "application/x-ext-djv" = "org.pwmt.zathura.desktop";
    "application/x-ext-djvu" = "org.pwmt.zathura.desktop";
    "application/x-ext-eps" = "org.pwmt.zathura.desktop";
    "application/x-ext-pdf" = "org.pwmt.zathura.desktop";
    "application/x-gzpdf" = "org.pwmt.zathura.desktop";
    "application/x-xzpdf" = "org.pwmt.zathura.desktop";
    "image/tiff" = "org.pwmt.zathura.desktop";
    "image/vnd.djvu+multipage" = "org.pwmt.zathura.desktop";
    "image/x-bzeps" = "org.pwmt.zathura.desktop";
    "image/x-eps" = "org.pwmt.zathura.desktop";
    "image/x-gzeps" = "org.pwmt.zathura.desktop";
    "x-scheme-handler/http" = "firefox.desktop";
    "x-scheme-handler/https" = "firefox.desktop";
    "x-scheme-handler/chrome" = "firefox.desktop";
    "text/html" = "firefox.desktop";
    "application/x-extension-htm" = "firefox.desktop";
    "application/x-extension-html" = "firefox.desktop";
    "application/x-extension-shtml" = "firefox.desktop";
    "application/xhtml+xml" = "firefox.desktop";
    "application/x-extension-xhtml" = "firefox.desktop";
    "application/x-extension-xht" = "firefox.desktop";
  };

  ##############################################################################
  # FONTS
  ##############################################################################

  # search installed fonts with: fc-list | grep -i <prefix>
  fonts.packages = with pkgs; [
    nerd-fonts.fira-code
    nerd-fonts.iosevka-term
    nerd-fonts.blex-mono
    nerd-fonts.jetbrains-mono
    monocraft
    fantasque-sans-mono
  ];
  # symlink fonts to /run/current-system/sw/share/X11/fonts
  fonts.fontDir.enable = true;

  ##############################################################################
  # QT
  ##############################################################################

  qt.enable = true;

  ##############################################################################
  # ENVIRONMENT
  ##############################################################################

  environment.localBinInPath = true;
  environment.variables = {
    QT_AUTO_SCREEN_SCALE_FACTOR = "1";
    QT_SCREEN_SCALE_FACTORS = "2";
    # QT_SCALE_FACTOR = "2"; # Useful for some apps, but multiplies with QT_SCREEN_SCALE_FACTORS for some?
    CUDA_PATH = "${pkgs.cudaPackages.cudatoolkit}";
    CUDNN_PATH = "${pkgs.cudaPackages.cudnn.lib}";
    OPENSSL_DIR = "${pkgs.openssl.dev}";
    OPENSSL_LIB_DIR = "${pkgs.openssl.out}/lib";
    OPENSSL_INCLUDE_DIR = "${pkgs.openssl.dev}/include";
    FONTS = "/run/current-system/sw/share/X11/fonts";
  };

  environment.systemPackages = with pkgs; [
    ### System
    wget
    inetutils # ftp, hostname, telnet
    patchelf # modify elf
    dig # DNS detective
    ngrok # expose localhost to the internet (dangerous)
    tcpdump # packet sniffer
    htop # task manager but cool
    man-pages # RTFM
    killall # murder processes
    asusctl # asus laptop controller
    lshw # hardware lister
    lsof # list open files
    neofetch # flex your setup
    starship # prompt that goes brrr
    appimage-run # run appimage executables
    # baobab # gnome disk usage analyzer
    foot # foot fetish stuff (wayland native terminal emulator)
    kitty # cat tools
    # quickemu # OS downloader
    pavucontrol # sound manager
    pciutils # lspci
    thunar # file manager
    gnome-network-displays # cast to TV
    # glance # web dashboard

    ### Nvidia stuff (the way it's meant to be played)
    cudaPackages.cuda_cudart
    cudaPackages.cudnn # deep neural networks
    cudaPackages.libcublas # basic linear algebra
    cudaPackages.cudatoolkit
    # cudaPackages.nsight_systems # profiler

    ### CLI tools
    dust # rust alt to "du" (disk usage visualizer)
    ripdrag # drag and drop from terminal
    calc # calculator
    zip # zip to .zip files
    unzip # unzip .zip files
    ouch # unzip various archives (stops you from saying ouch)
    p7zip # unzip everything
    sqlite # single file SQL database
    tmux # terminal multiplexer (many terminals in one)
    tlrc # "man" but shorter, fork of "tldr"
    file # get file info
    typioca # touch typing practice (for when typeracer.com is down)
    exiftool # metadata of file, more for images
    ripgrep # "grep" but faster (rip grep's performance)
    jq # JSON for terminal nerds
    fd # "find" but faster
    fzf # fuzzy finder
    tree # print file tree
    tre-command # like "tree" but "tre"
    # binsider # elf analyzer (binary deep dive)
    newsboat # RSS reader (for reading blogs like it's 2005)

    ### Monitoring tools (spy on your system)
    btop # general purpose (htop but beautiful)
    iotop # monitor disk usage
    nethogs # monitor network usage (who's eating bandwidth)
    nvtopPackages.nvidia # GPU monitor
    batmon # battery monitor
    powertop # battery monitor 2: electric boogaloo
    lm_sensors # type "sensors" to see cpu, gpu temps

    ### Regular programs
    # pomodoro-gtk # 25 minutes of focus (then break)
    # unison # file sync
    # syncthing # file sync (but actually works)
    # bitwarden-desktop # leak passwords to the cloud
    # keepassxc # offline passwords (paranoid mode)
    telegram-desktop # send messages to pavel durov
    qbittorrent # best torrenting program (totally legal use only)
    discord # modern forums (where gamers hang out)
    # anki # memorization helper (SRS for the win)
    # thunderbird # emails, just use browser
    graphviz # graphs visualization (make pretty diagrams)
    zathura # vim-like PDF reader
    # calibre # normal book reader (ebook library manager)
    kdePackages.okular # KDE PDF reader

    ### Graphics
    # krita # pro painter (digital art)
    # aseprite # pixel art (buy license!)
    # gimp # photoshop but worse, use photopea.com instead
    # pastel # colors in cli (for terminal aesthetics)
    loupe # gnome image viewer (simple and fast)

    ### Media
    # vlc # video player (plays everything, looks like 2003)
    mpv # video player but cooler (keyboard driven)
    ffmpeg # swiss army knife of media tools
    # opusTools # music format for the future (but not present)
    # yt-dlp # youtube pirate (arr matey)
    # pear-desktop # youtube pirate 2: the GUI strikes back
    # spotify # music subscription (monthly fee to listen)
    quodlibet # minimalistic audio player (python powered)
    # obs-studio # streamer tools (broadcast yourself)
    # lmms # music composing (free FL Studio)
    # blender # 3D everything (also makes donuts)
    # audacity # audio editor (cut and paste sounds)
    # godot_4 # game engine (open source unity)
    # apksigner # sign android apps

    ### Browsing
    firefox-bin # web browser (the good one)
    # qutebrowser # vim web browser (for keyboard addicts)
    # protonvpn-gui # vpn (privacy please)
    openvpn # open vpn
    # ungoogled-chromium # for emergency (chrome without google)
    google-chrome # for higher emergency (when nothing else works)

    ### Gaming
    # bottles # wine GUI (run windows games)
    # wineWowPackages.stableFull # not an emulator (it's a compatibility layer!)
    # winetricks # wine helper scripts
    # vulkan-tools # low level graphics API
    # antimicrox # map controller to keyboard
    # sc-controller # steam controller config
    # semeru-jre-bin-8 # java 8 for minecraft
    mangohud # FPS counter overlay (flex your frames)

    ### Chess (for the intellectuals)
    cutechess # GUI for UCI chess engines
    stockfish # best chess engine (will destroy you)
    lc0 # FOSS alphazero (neural network chess)
    # en-croissant # electron GUI (fancy analysis board)

    ### Text
    ed # standard text editor (from 1973)
    # zed-editor # rust GUI text editor (VSCode + Vim)
    # neovide # smooth GUI for neovim (animations go brrr)
    # hugo # static site generator (for your blog nobody reads)
    # pandoc # universal document converter
    # texlive.combined.scheme-small # LaTeX to PDF

    ### LLM (robot overlords)
    # lmstudio # local LLM GUI
    # gemini-cli # google's AI in terminal
    codex # openai code assistant
    claude-code # anthropic's helpful assistant (you're here!)
    # open-webui # self-hosted ChatGPT UI
    # librechat # another chat UI
    # code-cursor-fhs # AI-powered editor

    ### WEB tools
    # caddy # nginx but simpler (automatic HTTPS)
    # httpie # curl but pretty (python powered)
    nmap # network scanner (hecker stuff)
    subfinder # find subdomains with `subfinder -d google.com`
    # rustscan # nmap but faster (rust rewrite)
    # sshfs # freezes whole system, DO NOT USE

    ### DEV
    openssl # cryptography library
    nodejs_22 # javascript runtime
    # volta # nodejs version manager (switch node versions)
    gh # github cli
    just # "make" but modern
    zellij # rust tmux
    watchexec # run commands on file change (auto rebuild)
    jwt-cli # JWT token debugger
    tokei # count lines of code (flex your LOC)
    bat # "cat" but with syntax highlighting
    posting # TUI for API testing
    # postman # API testing (electron bloat)
    bruno # API testing (postman alternative)
    # insomnia # API testing (another alternative)
    redis # in-memory key-value store (fast cache)
    postgresql_14 # SQL database (the good one)
    mongosh # mongodb shell
    # mongodb-6_0 # EOL (end of life)
    mongodb-7_0 # NoSQL database (schema? what schema?)
    mongodb-compass # mongodb GUI
    mongodb-tools # mongodump, mongorestore, etc
    kubernetes # needed at work :-(
    yandex-cloud # too

    ### Python tools
    uv # python package manager (cargo for python, blazingly fast)
    # poetry # python package manager (slower but popular)
    ruff # python linter (implemented in rust, obviously faster)
    pyright # python LSP (from microsoft, surprisingly bad)
    pyrefly # python LSP
    # micromamba # conda alternative (full OS in your venv)
    # pipx # install python apps globally
    (pkgs.python312.withPackages (ps:
      with ps; [
        ipython
        pytest
        numpy
        # DAP
        debugpy
        # markdown
        grip # markdown preview
        guessit # guess media metadata
        # argostranslate # offline translate app
      ]))

    ### JS
    typescript # javascript but with types
    typescript-language-server # TS LSP

    ### Lua tools
    # lua # small programming language (moon language)
    # love # 2D game engine (make games with lua)

    ### Rust tools
    rustup # rust toolchain installer (setup.exe but better)

    ### Lean tools
    # elan # rustup for math (proof assistant)

    ### Nix tools
    nixd # nix LSP (code completion for nix)
    alejandra # nix formatter (makes nix files pretty)

    ### C/C++/asm tools
    gnumake # build system (classic)
    cmake # build system but harder (configuration hell)
    clang-tools # clangd LSP
    gcc # C/C++ compiler (GNU compiler collection)
    # clang # C/C++ compiler (conflicts with gcc)
    meson # build system in python (actually nice)
    gdb # GNU debugger (print debug statements are for noobs)
    strace # trace syscalls (see what programs really do)
    ltrace # trace library calls
    # trace-cmd # linux kernel tracer (deep dive)
    # kernelshark # kernel trace visualizer
    # gf # GUI debugger
    nasm # x86 assembler (write assembly like it's 1985)
    # valgrind # memory leak detector (find those segfaults)
    protobuf # binary serialization (google's data format)
    # blink # x86_64 emulator
    radare2 # reverse engineering toolkit (hacker vibes)
    # iaito # GUI for radare2
    # imhex # modern hex editor

    ### Android
    # android-studio # IDE for android apps
    # flutter # cross platform UI framework (dart language)

    ### Window manager (wayland supremacy)
    # river # tiling WM (kept for nostalgia)
    xdg-desktop-portal-wlr # screen sharing + file pickers
    swaybg # wayland wallpaper setter
    swaylock # lock screen (sleep with password)
    fnott # notification daemon (minimal)
    libnotify # test notifications (notify-send)
    lswt # list wayland windows (get window names)
    wayland-utils # show supported protocols
    grim # screenshot tool
    slurp # select screen region
    xwayland-satellite # xwayland per-app (legacy X11 support)
    fuzzel # app launcher + fuzzy finder
    bemoji # emoji picker (😎)
    cliphist # clipboard history
    alsa-utils # sound control (for volume buttons)
    brightnessctl # brightness control (for brightness buttons)
    wl-clipboard # wayland clipboard utilities
    wev # keyboard event viewer (find keycodes)
    waybar # status bar (shows stuff at top)
    gnome-themes-extra # Adwaita dark theme

    ### Custom scripts
    (pkgs.writeShellScriptBin "next_asus_profile" ./bin/next_asus_profile.sh)
    (pkgs.writeShellScriptBin "window_switch" ./bin/window_switch.sh)
    # (pkgs.writeShellScriptBin "ghidra_patch" ./bin/ghidra_patch.sh)

    ### Language servers
    lua-language-server # LSP for lua
    vscode-langservers-extracted # html/css/json/eslint LSPs
    # ltex-ls # grammar checker (markdown, latex)
    # ruff-lsp # python linter LSP
    marksman # markdown LSP
  ];

  ##############################################################################
  # NIX CONFIG
  ##############################################################################

  nixpkgs.config.allowUnfree = true;
  nixpkgs.config.cudaSupport = true;
  nixpkgs.config.permittedInsecurePackages = [
    "libsoup-2.74.3"
  ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  nix.settings.always-allow-substitutes = true;
  nix.settings.builders-use-substitutes = true;
  nix.settings.experimental-features = ["nix-command" "flakes"];
  nix.settings.auto-optimise-store = true;
  # nix.settings.max-jobs = "auto";
  nix.settings.max-jobs = 4;
  nix.settings.http-connections = 128;
  nix.settings.max-substitution-jobs = 128;
  nix.settings.substituters = [
    "https://cache.nixos.org/"
    "https://nix-community.cachix.org"
    "https://cuda-maintainers.cachix.org"
  ];
  nix.settings.trusted-public-keys = [
    "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
  ];
  nix.settings.trusted-substituters = [
    "https://nix-community.cachix.org"
    "https://cuda-maintainers.cachix.org"
  ];
  nix.settings.trusted-users = ["saegl"];
  nix.nixPath = ["nixpkgs=${inputs.nixpkgs}"]; # For nixd LSP

  ##############################################################################
  # SYSTEM
  ##############################################################################

  # NEVER CHANGE
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "23.11"; # Did you read the comment?
}
