# -*- conf -*-
# See `man foot.ini`

# shell=nvim

# font=FiraCode Nerd Font Mono:size=21.5
# font=Monocraft Nerd Font:size=21.5
# font=Fantasque Sans Mono:size=26.0
font=IosevkaTerm Nerd Font Propo:size=20.0

resize-by-cells=no

[mouse]
hide-when-typing=no

[colors-dark]
alpha=0.8
background=000000

[csd]
preferred=none

[key-bindings]
scrollback-up-line=Control+Shift+k
scrollback-down-line=Control+Shift+j
scrollback-up-page=Control+Shift+b
scrollback-down-page=Control+Shift+f
scrollback-up-half-page=Control+Shift+u
scrollback-down-half-page=Control+Shift+d
search-start=Control+Shift+slash
unicode-input=none

[search-bindings]
cancel=Control+c Escape
commit=Return
find-prev=Control+p
find-next=Control+n

# vim: ft=dosini
