# root
launch --title root
cd ~/projects/machineplay/

# backend
new_tab
launch --title backend
cd ~/projects/machineplay/backend/

# frontend
new_tab
launch --title frontend
cd ~/projects/machineplay/frontend/

# machineplay
new_tab
launch --title machineplay
cd ~/projects/machineplay/machineplay/

# python chess starter
new_tab
launch --title python-chess-starter
cd ~/projects/machineplay/python-chess-starter/

# malganis
new_tab
launch --title malganis
cd ~/projects/nix/malganis/
