# Dash
launch --title dash
cd ~/projects/ff/dash/

# VPN
new_tab
launch --title vpn
cd ~/projects/ff/dash/vpn/

# KUBE
new_tab
launch --title kube
cd ~/projects/ff/dash/kube/

# Gateway
new_tab
launch --title gateway
cd ~/projects/ff/gateway-service/

# Gateway Master
new_tab
launch --title gateway-master
cd ~/projects/ff/gateway-master/

# Gateway Review
new_tab
launch --title gateway-review
cd ~/projects/ff/bibisara/

# TODO: Add gateway review / gateway master

# Core
# new_tab
# launch --title core
# cd ~/projects/ff/core-service/

# Report
# new_tab
# launch --title report
# cd ~/projects/ff/report-service/

# AI-mcp
# new_tab
# launch --title ai-mcp
# cd ~/projects/ff/ai-mcp-service/

# Payment
# new_tab
# launch --title payment
# cd ~/projects/ff/payment-service/

# Classifier
# new_tab
# launch --title classifier
# cd ~/projects/ff/classifier-service/

# Calendar
# new_tab
# launch --title calendar
# cd ~/projects/ff/calendar-service/

# Utils
new_tab
launch --title utils
cd ~/projects/ff/finflow-utils/

# Core frontend
new_tab
launch --title core-front
cd ~/projects/ff/core-frontend/

# Report JSS
new_tab
launch --title report-jss
cd ~/projects/ff/report-jss/

# OTP
new_tab
cd ~/projects/ff/dash/otp/
launch --title otp --hold just

# db
new_tab
cd ~/projects/ff/dash/db/
launch --title db --hold just

# admin
new_tab
launch --title admin
cd ~/projects/ff/admin-frontend/

# converter
# new_tab
# launch --title converter
# cd ~/projects/ff/converter/
