#!/bin/sh

# Set background and border color
riverctl background-color 0x0b0b10  # rosepine hl_low +0.1 darken
riverctl border-color-focused 0x908caa  # rosepine subtle
riverctl border-color-unfocused 0x191724  # rosepine base

# Notifications
riverctl map normal Super D spawn "fnottctl dismiss"
riverctl map normal Super A spawn "fnottctl actions"

# Launcher
riverctl map normal Super R spawn fuzzel
riverctl map normal Super E spawn bemoji
riverctl map normal Super V spawn "cliphist list | fuzzel -d | cliphist decode | wl-copy"
riverctl map normal Super Q spawn powermenu
riverctl map normal Super T spawn foot
riverctl map normal Super B spawn firefox
riverctl map normal Super P spawn "foot -a float -T float"
riverctl map normal Super Y spawn "foot -a float -T float yazi"
riverctl map normal Super N spawn "foot -a float -T float nvim"
riverctl map normal Super O spawn "foot -a float -T float ollama run llama3.2"

# Screenshots
riverctl map normal Shift+Super S spawn "sh -c 'prefix=\"Part_\"; filename=/home/saegl/screenshots/\$prefix\$(date +%Y-%m-%d_%H-%M-%S).png; grim -g \"\$(slurp -d)\" \"\$filename\" && notify-send \"Saved at \$filename\" --app-name=\"Screenshot\"'"
riverctl map normal Super S spawn "sh -c 'prefix=\"Full_\"; filename=/home/saegl/screenshots/\$prefix\$(date +%Y-%m-%d_%H-%M-%S).png; grim \"\$filename\" && notify-send \"Saved at \$filename\" --app-name=\"Screenshot\"'"

riverctl map normal Super C close # Close focused window
riverctl map normal Super+Shift E exit  # Exit river

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal


# Hyper mode
riverctl declare-mode hyperm
riverctl map normal None Hyper_L enter-mode hyperm
riverctl map hyperm None Escape enter-mode normal
riverctl map hyperm None a spawn 'riverctl set-focused-tags 1 && riverctl enter-mode normal'
riverctl map hyperm None s spawn 'riverctl set-focused-tags 2 && riverctl enter-mode normal'
riverctl map hyperm None d spawn 'riverctl set-focused-tags 4 && riverctl enter-mode normal'
riverctl map hyperm None f spawn 'riverctl set-focused-tags 8 && riverctl enter-mode normal'

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'amixer set Master 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'amixer set Master 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'amixer set Master toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'


    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set keyboard repeat rate
riverctl set-repeat 40 350
riverctl keyboard-layout -options 'grp:alt_shift_toggle,caps:hyper' us,ru


#################### RULES
# riverctl rule-add ssd
riverctl rule-add -app-id 'float' -title 'float' float
riverctl rule-add -app-id 'float' -title 'float' dimensions 1600 1000

#################### Inputs configuration
riverctl input pointer-1267-12703-ASUE1209:00_04F3:319F_Touchpad natural-scroll enabled
riverctl input pointer-1267-12703-ASUE1209:00_04F3:319F_Touchpad tap enabled


#################### Autostart
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &
riverctl spawn 'exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river'
# riverctl spawn 'yambar'
riverctl spawn 'waybar -s /home/saegl/.config/waybar/style_minimal.css'
# riverctl spawn 'wbg ~/projects/nix/nixos/wallpapers/winter_tree.png'
riverctl spawn 'swaybg -i /home/saegl/projects/nix/nixos/wallpapers/winter_tree.png'
riverctl spawn 'wl-paste --watch cliphist store'
