# -*- conf -*-

# Docs: `man fnott.ini`

selection-helper=fuzzel -d

layer=overlay
# vesper (matches kitty + nvim + fuzzel)
background=101010ff
border-color=505050ff
dpi-aware=yes

# Timeout values are in seconds. 0 to disable
max-timeout=30
