# -*- conf -*-

# Docs: `man fnott.ini`

selection-helper=fuzzel -d

layer=overlay
background=26233aee
border-color=1f1d2eff
dpi-aware=yes

# Timeout values are in seconds. 0 to disable
max-timeout=30
